apiVersion: apps/v1
kind: Deployment
metadata:
  name: areyouok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: areyouok
  template:
    metadata:
      labels:
        app: areyouok
    spec:
      containers:
      - name: areyouok
        image: martinfylke/areyouok:1.0.1
        ports:
          - containerPort: 80
        env:
        - name: HEALTH_POLL_RATE_SECONDS
          value: "60"
        - name: DB_PROVIDER
          value: "postgres"
        - name: DB_CONNECTION_STRING
          value: "User ID=postgres;Password=postgres;Host=postgresql;Port=5432;Database=areyouok;"
        - name: HEALTH_ENDPOINTS
          value: "endpoint1 endpoint2"
        - name: DATA_RETENTION_DAYS
          value: "30"
---
apiVersion: v1
kind: Service
metadata:
  name: areyouok
spec:
  ports:
  - port: 30010
    protocol: TCP
    targetPort: 80
  selector:
    app: areyouok
  type: LoadBalancer